//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mac_EFI_Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mac_EFI_Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terms outlined below pertain to the usage of the Mac EFI Toolkit
        ///software. Throughout these terms, &quot;The user&quot; and &quot;You&quot; refer to any
        ///individual or group utilizing the software, while &quot;The Author&quot; denotes
        ///the software developer, David Roberts, also known as &quot;Muerto.&quot;
        ///
        ///When engaging in actions such as removing a digital lock or altering
        ///a product&apos;s digital serial number, it is crucial to either legally
        ///possess the device or obtain appropriate legal authorization, which
        ///may include possessing the o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editorterms {
            get {
                return ResourceManager.GetString("editorterms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgmuerto64px {
            get {
                object obj = ResourceManager.GetObject("imgmuerto64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgSprite {
            get {
                object obj = ResourceManager.GetObject("imgSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo32px {
            get {
                object obj = ResourceManager.GetObject("logo32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo64px {
            get {
                object obj = ResourceManager.GetObject("logo64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;data&gt;
        ///    &lt;section&gt;
        ///        &lt;cfgCode&gt;000&lt;/cfgCode&gt;
        ///        &lt;model&gt;Power Mac G5&lt;/model&gt;
        ///    &lt;/section&gt;
        ///    &lt;section&gt;
        ///        &lt;cfgCode&gt;00W&lt;/cfgCode&gt;
        ///        &lt;model&gt;Xserve (Late 2006)&lt;/model&gt;
        ///    &lt;/section&gt;
        ///    &lt;section&gt;
        ///        &lt;cfgCode&gt;01P&lt;/cfgCode&gt;
        ///        &lt;model&gt;MacBook (13-inch, Late 2007)&lt;/model&gt;
        ///    &lt;/section&gt;
        ///    &lt;section&gt;
        ///        &lt;cfgCode&gt;01V&lt;/cfgCode&gt;
        ///        &lt;model&gt;MacBook (13-inch, Late 2007)&lt;/model&gt;
        ///    &lt;/section&gt;
        ///    &lt;section&gt;
        ///        &lt;cf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modeldb {
            get {
                return ResourceManager.GetString("modeldb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] segmdl2 {
            get {
                object obj = ResourceManager.GetObject("segmdl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
